Add STI models for wagons and additional AR features
rohellec/tutu pull request #2
Opened 2017-10-30 20:42 UTC by rohellec

2017-10-31 06:14 UTC, vkurennov requested changes

2017-10-31 06:14 UTC, vkurennov commented on app/controllers/wagons_controller.rb
> +    params.require(:wagon).permit(:train_id, :wagon_type, :bottom_places, :upper_places,
Почему тут wagon_type? У нас же теперь STI, нужно использовать поле type

2017-10-31 06:14 UTC, vkurennov commented on app/models/railway_station.rb
> +  scope(:route_order, lambda do
При задании скоупа не принято ставить скобки, а лямбду принято задвать с помощью литерала `->` и блок через фигурные скобки

2017-10-31 06:14 UTC, vkurennov commented on app/models/railway_station.rb
> +  end)
Скобка после end выглядит особенно не по-рубишному

2017-10-31 06:14 UTC, vkurennov commented on app/views/wagons/_form.html.erb
> +    <%= form.label  :wagon_type %>
Мы должны использовать поле type, которое и работает с STI, wagon_type, это твое поле.

2017-10-31 06:14 UTC, vkurennov commented on app/models/wagons/wagon.rb
> +  def with_exact_type
Цель в том, чтобы попробовать возможности STI в действии, чтобы рельсы всю эту работу сделали автоматически. А ты по факту, написал свою реализацию STI, что хорошо для понимания его работы, но в задании требуется другое.

2017-11-02 05:35 UTC, iBublik approved these changes

2017-11-02 05:35 UTC, iBublik commented on app/models/wagons/wagon.rb
> +    TYPES.find { |_key, value| value == type }.first
Как-то сложно получилось. Можно ведь инвертировать хеш (поменять ключи и значения местами) и обращаться через `[]`.
А можно еще проще поступить - в базовом классе просто объявить пустой метод `display_name`. А в наследниках его переопределить, так чтобы SittingWagon возвращал Sitting, EconomWagon - Econom и т.д.

2017-11-02 05:35 UTC, iBublik commented on app/models/wagons/wagon.rb
> +  belongs_to :train, optional: true
Почему эта связь необязательна? Разве имеет смысл вагон без поезда?

2017-11-02 05:35 UTC, iBublik commented on app/models/wagons/wagon.rb
> +  before_save :set_ordinal, if: ->(wagon) { wagon.changes["train_id"] }
`if: :train_id_changed?`

2017-11-02 05:35 UTC, iBublik commented on app/models/wagons/wagon.rb
> +    self.ordinal = train.wagons.any? ? train.wagons.maximum(:ordinal) + 1 : 1
Тут условие только усложняет понимание - `train.wagons.maximum(:ordinal).to_i + 1`

2017-11-02 05:35 UTC, iBublik commented on app/views/trains/show.html.erb
> +  <% if @train.wagons.empty? %>
Общая рекомендация - обрабатывай сначала "основные" потоки выполнения в условиях. Нам ведь важнее понимать, что выведется при наличии вагонов. Так что поменяй условие на `any?` и вынеси вверх вывод списка вагонов

2017-11-02 05:35 UTC, iBublik commented on db/migrate/20171029071154_add_wagon_direction_to_train.rb
> +    add_column :trains, :head_direction, :boolean
Для булеан полей лучше взять за правило устанавливать дефолтное значение и добавлять `null: false`. Иначе это будет tristate-поле - `true/false/null`, а это не очень удобно

2017-11-02 11:36 UTC, vkurennov approved these changes

2017-11-02 20:01 UTC, merged