Controllers and forms
rohellec/tutu pull request #3
Opened 2017-11-09 19:54 UTC by rohellec

2017-11-10 04:25 UTC, iBublik requested changes

2017-11-10 04:25 UTC, iBublik commented on app/controllers/wagons_controller.rb
> +    @wagon = @wagon.becomes(params[:wagon][:type].constantize)
Тут лучше `wagon_params` использовать. Так избежим ошибки, если в контроллер не передали хэш `wagon` в параметрах

2017-11-10 04:25 UTC, iBublik commented on app/controllers/wagons_controller.rb
> +  def set_train
Из `wagon_params` нужно выбросить `train_id`

2017-11-10 04:25 UTC, iBublik commented on app/controllers/searches_controller.rb
> +    @search_results = available_trains(base, final).inject([]) do |result, train|
Много логики для контроллера. Стоит вынести в обычный Ruby класс (например, Search)

2017-11-10 04:25 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route = station_route(route)
Зачем в переменную записывать? У тебя ведь есть мемоизация в методе `station_route`

2017-11-10 04:25 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route.update(position: position)
А если не нашли станцию?

2017-11-10 04:25 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route(route).arrival_time.strftime("%k:%M")
Тут тоже может упасть, если станция не найдена

2017-11-10 04:25 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route(route).try(:position)
Рекомендую отказываться от `try` в пользу `&` (safe navigation operator). `try` позволяет вызывать на объекте методы, которых у него нет

2017-11-10 04:25 UTC, iBublik commented on app/models/railway_station.rb
> +    @station_route ||= railway_stations_routes.where(route: route).take
Можно немного сократить запись - `railway_stations_routes.find_by(route: route)`

2017-11-10 04:25 UTC, iBublik commented on app/models/route.rb
> +    all.find_all { |route| route.pass_through?(base, final) }
Скоупы должны быть `chainable`. У тебя же тут вернется массив. Так что надо выносить это из скоупа (в метод класса или отдельный класс поиска)

2017-11-10 04:25 UTC, iBublik commented on app/models/route.rb
> +    all.find_all { |route| route.pass_through?(base, final) }
И у тебя тут весь перебор идет на Ruby. Это очень неэффективно. Надо реализовать с помощью БД (хинт - сделай 2 запроса: один ищет маршруты с начальной станцией, другой с конечной, их пересечение уже на рубях можно вычислить)

2017-11-11 10:27 UTC, vkurennov approved these changes

2017-11-11 10:27 UTC, vkurennov commented on app/models/railway_station.rb
> +    @station_route&.update(position: position)
Так можно до одной строки сократить, зачем к переменной привязываться: `station_route(route)&.update(position: position)`

2017-11-13 20:36 UTC, merged